embeds:
  - title: Yelan
    color: ${ COLORS.HYDRO_BLUE }
    image: 
      url: ${INFOGRAPHICS.YELAN_1}
    thumbnail:
      url: ${ICON.CHARACTER_YELAN}
    description: |-
      ★★★★★
      *Hydro Bow*
    footer:
      text: "Use \"Open original\" to view full size.\n\nCredits to: xf3#3123 (Designer) | KB#1111 & Vladone ツ#9281 (Content)"


buttons:
  - customId: "liveInteraction#characters/hydro/yelan/yelan_team"
    label: "Teams Infographic"
    style: "PRIMARY"
    emoji: "▶️"

  - customId: "liveInteraction#faq/yelaner"
    label: "ER Requirements"
    style: "PRIMARY"
    emoji: ${ EMOJIS.ENERGY_RECHARGE }

  - label: "Guide"
    url: "https://keqingmains.com/yelan"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "Quick Guide"
    url: "https://keqingmains.com/q/yelan-quickguide/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "TCL"
    url: "https://library.keqingmains.com/yelan"
    emoji: ${ EMOJIS.MAGNIFY }
    style: "LINK"