embeds:
  - title: Yoimiya
    color: ${ COLORS.PYRO_ORANGE }
    image: 
      url: ${INFOGRAPHICS.YOIMIYA_1}
    thumbnail:
      url: ${ICON.CHARACTER_YOIMIYA}
    description: |-
      ★★★★★
      *Pyro Bow*
    footer:
      text: "Use \"Open original\" to view full size.\n\nCredits to: euphorysm#1618 (Designer) | Ayzel#7399 (Content)"

buttons:
  - label: "Guide"
    url: "https://keqingmains.com/yoimiya/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "Quick Guide"
    url: "https://keqingmains.com/q/yoimiya-quickguide/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "TCL"
    url: "https://library.keqingmains.com/characters/pyro/yoimiya"
    emoji: ${ EMOJIS.MAGNIFY }
    style: "LINK"

  - label: "Video Guide"
    url: "https://youtu.be/FjDsbxPbk50"
    emoji: ${ EMOJIS.YOUTUBE }
    style: "LINK"