embeds:
  - title: Lyney
    color: ${ COLORS.PYRO_ORANGE }
    image: 
      url: ${ INFOGRAPHICS.LYNEY_1 }
    thumbnail:
      url: ${ICON.CHARACTER_LYNEY}
    description: |-
      ★★★★★
      *Pyro Bow*
    footer:
      text: "Use \"Open original\" to view full size.\n\nCredits to: cuppacote (Content & Designer)"

buttons:
  - label: "Quick Guide"
    url: "https://keqingmains.com/q/lyney-quickguide/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "TCL"
    url: "https://library.keqingmains.com/characters/pyro/lyney"
    emoji: ${ EMOJIS.MAGNIFY }
    style: "LINK"