embeds:
  - title: Dendro Traveler
    color: ${COLORS.DENDRO_GREEN}
    image: 
      url: ${INFOGRAPHICS.DENDRO_TRAVELER_1}
    thumbnail:
      url: ${ICON.CHARACTER_TRAVELER_M}
    description: |-
      ★★★★★
      *Dendro Sword*
    footer:
      text: "Use \"Open original\" to view full size. Page 2 Coming Soon!\n\nCredits to: angtahimik (Designer) | anticipaste (Content)" 
    


buttons:

#  - label: "Guide"
#    url: "https://keqingmains.com/"
#    emoji: ${ EMOJIS.LOGO }
#    style: "LINK"

  - label: "Quick Guide"
    url: "https://keqingmains.com/q/dendro-traveler-quickguide/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "TCL"
    url: "https://library.keqingmains.com/dmc"
    emoji: ${ EMOJIS.MAGNIFY }
    style: "LINK"