embeds:
  - title: Barbara
    color: ${ COLORS.HYDRO_BLUE }
    image: 
      url: ${INFOGRAPHICS.BARBARA_1}
    thumbnail:
      url: ${ICON.CHARACTER_BARBARA}
    description: |-
      ★★★★
      *Hydro Catalyst*
    footer:
      text: "Use \"Open original\" to view full size.\n\nCredits to: Artesians#0002 (Designer) | xf3#3123 (Content)"      


buttons:
  - customId: "liveInteraction#characters/hydro/barbara/build"
    label: "Teams Infographic"
    style: "PRIMARY"
    emoji: "▶️"

  - label: "Guide"
    url: "https://keqingmains.com/barbara"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "Quick Guide"
    url: "https://keqingmains.com/q/barbara-quickguide/"
    emoji: ${ EMOJIS.LOGO }
    style: "LINK"

  - label: "TCL"
    url: "https://library.keqingmains.com/barbara"
    emoji: ${ EMOJIS.MAGNIFY }
    style: "LINK"